sudo: required
language: php
php:
    - 7.1
services:
    - docker
before_script:
    - composer install --prefer-source
    - docker build . -t test_server_status
script: docker run -it --rm -v "$PWD":/usr/src/lib test_server_status
after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
notifications:
    slack: innmind:nAiLaAi6RU4wGEAdL6FuKdyF
