language: php
php:
    - 7.1
    - 7.2
    - nightly
matrix:
    allow_failures:
        - php: nightly
before_script: composer install --prefer-source
script: vendor/bin/phpunit
after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
